### ISSUE TITLE
Gemfile using master branch

### ISSUE THREAD

**Issue by wilkosz** [winebarrel/activerecord-mysql-reconnect#16]
# Issue 
Using master branch breaking rails

`Gemfile`
```ruby
gem 'activerecord-mysql-reconnect', git: 'https://github.com/winebarrel/activerecord-mysql-reconnect.git'
```

```bash
Traceback (most recent call last):
	54: from bin/rails:5:in `<main>'
	53: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
	52: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	51: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
	50: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	49: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	48: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	47: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	46: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	45: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/railties-5.2.4.2/lib/rails/commands.rb:18:in `<top (required)>'
	44: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/railties-5.2.4.2/lib/rails/command.rb:46:in `invoke'
	43: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/railties-5.2.4.2/lib/rails/command/base.rb:69:in `perform'
	42: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	41: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	40: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	39: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/railties-5.2.4.2/lib/rails/commands/console/console_command.rb:95:in `perform'
	38: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/railties-5.2.4.2/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
	37: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/railties-5.2.4.2/lib/rails/command/actions.rb:28:in `require_environment!'
	36: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/railties-5.2.4.2/lib/rails/application.rb:337:in `require_environment!'
	35: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
	34: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	33: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
	32: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	31: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	30: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	29: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	28: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	27: from /Users/joshuawilkosz/GithHub/dochub/config/environment.rb:5:in `<top (required)>'
	26: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/railties-5.2.4.2/lib/rails/railtie.rb:190:in `method_missing'
	25: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/railties-5.2.4.2/lib/rails/railtie.rb:190:in `public_send'
	24: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/railties-5.2.4.2/lib/rails/application.rb:361:in `initialize!'
	23: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/railties-5.2.4.2/lib/rails/initializable.rb:60:in `run_initializers'
	22: from /Users/joshuawilkosz/.rvm/rubies/ruby-2.5.7/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	21: from /Users/joshuawilkosz/.rvm/rubies/ruby-2.5.7/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	20: from /Users/joshuawilkosz/.rvm/rubies/ruby-2.5.7/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	19: from /Users/joshuawilkosz/.rvm/rubies/ruby-2.5.7/lib/ruby/2.5.0/tsort.rb:347:in `call'
	18: from /Users/joshuawilkosz/.rvm/rubies/ruby-2.5.7/lib/ruby/2.5.0/tsort.rb:347:in `each'
	17: from /Users/joshuawilkosz/.rvm/rubies/ruby-2.5.7/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
	16: from /Users/joshuawilkosz/.rvm/rubies/ruby-2.5.7/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
	15: from /Users/joshuawilkosz/.rvm/rubies/ruby-2.5.7/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	14: from /Users/joshuawilkosz/.rvm/rubies/ruby-2.5.7/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
	13: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/railties-5.2.4.2/lib/rails/initializable.rb:61:in `block in run_initializers'
	12: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `run'
	11: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `instance_exec'
	10: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.2/lib/active_record/railtie.rb:132:in `block in <class:Railtie>'
	 9: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/lazy_load_hooks.rb:42:in `on_load'
	 8: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/lazy_load_hooks.rb:42:in `each'
	 7: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/lazy_load_hooks.rb:43:in `block in on_load'
	 6: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
	 5: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
	 4: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
	 3: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/lazy_load_hooks.rb:71:in `instance_eval'
	 2: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.2/lib/active_record/railtie.rb:133:in `block (2 levels) in <class:Railtie>'
	 1: from /Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/railties-5.2.4.2/lib/rails/application/configuration.rb:165:in `database_configuration'
/Users/joshuawilkosz/.rvm/gems/ruby-2.5.7/gems/railties-5.2.4.2/lib/rails/application/configuration.rb:190:in `rescue in database_configuration': YAML syntax error occurred while parsing /Users/joshuawilkosz/GithHub/dochub/config/database.yml. Please note that YAML must be consistently indented using spaces. Tabs are not allowed. Error: (<unknown>): did not find expected ',' or ']' while parsing a flow sequence at line 41 column 13 (RuntimeError)
```

`database.yml`
![Screen Shot 2020-05-07 at 10 13 34 am](https://user-images.githubusercontent.com/2351142/81240703-79491100-904b-11ea-87ae-eb016a249ce4.png)

**Comment by wilkosz** [comment]
AWS Secrets manager default lambda generates passwords with special characters which invalidate YAML syntax!
